// Generated by hand from the Firebase project `xenon-world-502717-f0`
// (equivalent to what `flutterfire configure` would produce). These values
// are safe to commit — Firebase client config is not a secret; access is
// controlled by Firebase Auth + security rules, not by hiding this file.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjZ4WcBnJUyKze292omiOV08CTPb5z08',
    appId: '1:1042221686578:web:773473ce8a1a5ffa0c812b',
    messagingSenderId: '1042221686578',
    projectId: 'xenon-world-502717-f0',
    authDomain: 'xenon-world-502717-f0.firebaseapp.com',
    storageBucket: 'xenon-world-502717-f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUjPFRaBIQcXQ1zu10qxheCB4JnpoXu5k',
    appId: '1:1042221686578:android:7e4f05fb2b834dd10c812b',
    messagingSenderId: '1042221686578',
    projectId: 'xenon-world-502717-f0',
    storageBucket: 'xenon-world-502717-f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMzoFEadNNQsCRCAFUXdutxeRuLK-bFI0',
    appId: '1:1042221686578:ios:be1d32ab4e1735900c812b',
    messagingSenderId: '1042221686578',
    projectId: 'xenon-world-502717-f0',
    storageBucket: 'xenon-world-502717-f0.firebasestorage.app',
    iosBundleId: 'com.spendsense.spendsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMzoFEadNNQsCRCAFUXdutxeRuLK-bFI0',
    appId: '1:1042221686578:ios:be1d32ab4e1735900c812b',
    messagingSenderId: '1042221686578',
    projectId: 'xenon-world-502717-f0',
    storageBucket: 'xenon-world-502717-f0.firebasestorage.app',
    iosBundleId: 'com.spendsense.spendsense',
  );
}
